// Mocks generated by Mockito 5.2.0 from annotations
// in bloc_project/test/blog_posts_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:bloc_project/core/models/blog_post_model.dart' as _i4;
import 'package:bloc_project/core/services/blogs_api_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [BlogsApiProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlogsApiProvider extends _i1.Mock implements _i2.BlogsApiProvider {
  MockBlogsApiProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.BlogPostModel>> fetchblogPosts() =>
      (super.noSuchMethod(Invocation.method(#fetchblogPosts, []),
              returnValue:
                  Future<List<_i4.BlogPostModel>>.value(<_i4.BlogPostModel>[]))
          as _i3.Future<List<_i4.BlogPostModel>>);
}
